common: &SHARED
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: password
  
development:
  <<: *SHARED
  database: sencha_sandbox_dev

test:
  <<: *SHARED
  database: sencha_sandbox_test

staging:
  <<: *SHARED
  database: sencha_sandbox_staging
    
production:
  <<: *SHARED
  database: sencha_sandbox_production
